version: '3'

volumes:
  pg_kitty_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_kitty_data_production:/var/lib/postgresql/data
  backend:
    image: zaylyalow/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/cats/images/
  frontend:
    image: zaylyalow/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: zaylyalow/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media/cats/images/
    ports:
      - 9000:80